
remote_theme: Forty
# site settings
title: Ronak Shah
subtitle: Personal Website
email: Ronakpshah1115@gmail.com
description: My personal website to learn more about my work and life. Come explore with me!
baseurl: "/PersonalWebsite" # the subpath of your site, e.g. /blog
url: "https://ronakps.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br
author:
city: Austin
state: TX
country: United States of America
phone: (214) 402-9561

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/ronakps
  LinkedIn: https://www.linkedin.com/in/ronakps/

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
